config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :users
  root 'places#index'
  resources :places
  resources :places do
    resources :comments, only: :create
  end

  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  geocoded_by :address
  after_validation :geocode
  validates :name, presence: true, length: { minimum: 4 }
  validates :address, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end
  
  def new
    @places = Place.new
  end
  
  def create
    @places = current_user.places.create(place_params)
      if @places.valid?
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
  end
  
  def show
    @place = Place.find(params[:id])
  end
  
  def edit
    @place = Place.find(params[:id])
  end

  def update
      @place = Place.find(params[:id])
      @place.update_attributes(place_params)
      redirect_to root_path
  end
  
  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to root_path
  end
  
  before_action :authenticate_user!, only: [:new, :create]
  
  @comment = Comment.new
  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
</head>
<body class="inner">

<nav class="navbar navbar-inverse" role="navigation”>
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to 'Yumster', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Add Place', new_place_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
<% end %>

<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Edit Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %><br />
    <%= f.input :address %><br />
    <%= f.input :description %>
    <br />
    <%= f.submit 'Edit', class: 'btn btn-info center-block' %>
  <% end %>
</div>

app/views/places/index.html.erb
<% @places.each do |place| %>
  <div class = "box text-center inner">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <h3><%= place.address %></h3>
    <h3><%= place.description %></h3>
    <div class="pull-right">
  </div>
  <% if place.user.present? %>
        <small><%= place.user.email %></small>
  <% end %>
  </div><br>
  
<% end %>

app/views/places/new.html.erb
<div class="box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @places do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="box col-xs-10 col-xs-offset-1 text-center">
    <% if @place.latitude.present? && @place.longitude.present? %>
    <script>
      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: myLatLng
        });
        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC9UoH_ACfC6U1UrzVYyO_B_GLXtMuSgvs&callback=initMap">
    </script>  

    <div id="map"></div><br/>
    <% end %>

  <br/>
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>
  <div class="pull-right">
    <% if current_user && current_user == @place.user %>
        <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
    <% end %>
  </div>
  
  <% if current_user && current_user == @place.user %>
    <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger pull-left' %>
  <% end %>
  
   <div class="text-center clear">
  <br/><br/>
  <u><h2>Post your Comment</h2></u><br/>
  <%= simple_form_for Comment.new , url: place_comments_path(@place) do |f| %>
    <%= f.input :message %><br/>
    <%= f.input :rating %>
    <br/>
    <%= f.submit "Add a Comment", class: 'btn btn-success' %>
  <% end %>
  </div>
  <br/>

</div>

<% if !(@place.comments.empty?) %>
  <div class="text-center clear">
    <u><h1>Comments</h1></u><br/>
    <% @place.comments.each do |comment| %>
      <div class="col-sm-6 center-block">
      <blockquote>
        <b><%= comment.rating %></b> -
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %><br/>
</div>
<% end %>